branches:
  only:
  - enhancements-jl-deployment        # Testing-*ONLY* branch => Comment out to disable!
  - master                            # Production branch
  - /^develop.*$/                     # Development branch and derivates
sudo: false
language: node_js
node_js:
- '5'
notifications:
  webhooks:
    on_success: change
    on_failure: always
script:
  - bash ./build-scripts/build.sh
env:
  global:
cache:
  directories:
    - node_modules

