sudo: false
language: node_js
node_js:
  - '5'
notifications:
webhooks:
    on_success: change
    on_failure: always
script:
  - $TRAVIS_BRANCH == "develop" && bash ./build-scripts/deploy-development.sh
env:
  global:
  - GITHUB_REPO: victoriauniversity/vuw-styleguide
  - secure: AcQTkjyTcBidnG3177dYz1aqXwPj0lCgY63Q/E8rZRVdgwQZbKw9DZ75q/8pcJmYsyp+C4WGbiMUQxwNzf9ALb4P42kIutnaq/EUaR8szBgKKl4MOHdDFHT8W19F3/ZrB+NBUNy6R5JeORu2ZNZpqBdshpWDRFzIMdyqgcjfkmWNpf3yiiHBwbqId/hYFgpFT8Ac3McdrGh/6bqVJTUb+mXx0UsJfQOebfpwLNUXIabrrms0FL1jTbZPhW66C6sEAG5Mxv/cYWaXq8QnS65SoOltSvJL+rXmN6iKgP+OEO4Gngt+x2NIZ/6dFITo5X3AMhSU2yC+Wq/SnJMONoEQAwHaDZdADqGaMZ0y6WK2x7VN6fwCuwrgQBzvbeobm94rGx3tHEFSBq3xZ8qWWl3OgZqLk9NkujKPdQOXSJmao0SyP9cJus9XevB4TjEZ1/GWITs0NkC9MfCYJ/Y8hUfJTUqFSRIAOKx2zD7OWaHMhGe9anc9sBYJczY43YCL2f7gOQkzpnxa8x3CwvfKlQS1KC1lWLWvEqvVhaW0Sfhzx3ULKxjADdxeFE1gOr4kapM8ZhSoKsl27IOSx8EJLKTU2gyS8sOC2iTW9YxcWrYsrlhlhU9W0fbIpvEcFAJsNpv+D6UsLU/4f1S+tQkjy5q9RiGYILRjzAU3uObVI1/TZ+g=
cache:
  directories:
    - node_modules
